.PHONY: test
.PHONY: test-real

test:
	dotnet test TestDataDefinitionFramework.Testing.ExampleTests/TestDataDefinitionFramework.Testing.ExampleTests.csproj
	
test-real:
	dotnet test TestDataDefinitionFramework.Testing.ExampleTests/TestDataDefinitionFramework.Testing.ExampleTests.csproj -c=Debug-RealProviderMode